--조유담
CREATE TABLE `dam_movie` 
(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `영화명`	varchar(300),
    `영화명(영문)`	varchar(300),
    `제작연도`	varchar(300),
    `장르`	varchar(300),
    `감독`	varchar(300),
    `제작사`	varchar(300)
    
);


-- 홍진서 
CREATE TABLE movie_info (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SN DECIMAL(30,0),
    MOVIE_NM VARCHAR(200),
    MNG_NM VARCHAR(200),
    MAKR_NM VARCHAR(200),
    IMPORT_CMPNY_NM VARCHAR(200),
    DISTB_CMPNY_NM VARCHAR(200),
    OPEN_DE VARCHAR(8),
    MOVIE_TY_NM VARCHAR(200),
    MOVIE_STLE_NM VARCHAR(200),
    NLTY_NM VARCHAR(200),
    WNTY_SCREEN_CO DECIMAL(28,5),
    WNTY_SELNG_AM DECIMAL(28,5),
    WNTY_AUDE_CO DECIMAL(28,5),
    SU_SELNG_AM DECIMAL(28,5),
    SU_AUDE_CO DECIMAL(28,5),
    GENRE_NM VARCHAR(200),
    GRAD_NM VARCHAR(200),
    MOVIE_SE VARCHAR(30)
);
