-- 홍진서 
CREATE TABLE user(
    id VARCHAR(15) NOT NULL PRIMARY KEY,
    pwd VARCHAR(20) NOT NULL,
    username VARCHAR(30) NOT NULL
);

CREATE TABLE movie_info (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SN DECIMAL(30,0),
    MOVIE_NM VARCHAR(200),
    MNG_NM VARCHAR(200),
    MAKR_NM VARCHAR(200),
    IMPORT_CMPNY_NM VARCHAR(200),
    DISTB_CMPNY_NM VARCHAR(200),
    OPEN_DE VARCHAR(8),
    MOVIE_TY_NM VARCHAR(200),
    MOVIE_STLE_NM VARCHAR(200),
    NLTY_NM VARCHAR(200),
    WNTY_SCREEN_CO DECIMAL(28,5),
    WNTY_SELNG_AM DECIMAL(28,5),
    WNTY_AUDE_CO DECIMAL(28,5),
    SU_SELNG_AM DECIMAL(28,5),
    SU_AUDE_CO DECIMAL(28,5),
    GENRE_NM VARCHAR(200),
    GRAD_NM VARCHAR(200),
    MOVIE_SE VARCHAR(30)
);


--이유림
CREATE TABLE movie_boxoffice_ranking (
	ranking INT NOT NULL,
	title VARCHAR(255) NOT NULL PRIMARY KEY,
    date VARCHAR(255) NOT NULL,
    sales VARCHAR(255) NOT NULL,
    audience VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    distributor VARCHAR(255) NOT NULL
);
